services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: web
      args:
        DATABASE_URL: ${DATABASE_URL}
        DIRECT_URL: ${DIRECT_URL}
    env_file:
      - ./.env.production
    ports:
      - "3000:3000"
    restart: unless-stopped

  worker:
    build:
      context: .
      dockerfile: Dockerfile
      target: worker
      args:
        DATABASE_URL: ${DATABASE_URL}
        DIRECT_URL: ${DIRECT_URL}
    env_file:
      - ./.env.production
    restart: unless-stopped
